### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by IlyaMokin** [IvanMenshov/whatsapp-ui#1]
Hello @IvanMenshov,
Looks cool! Thanks for the efforts. 
Please add also different types of messages to the UI
 - audio
 - link with a preview
 - response with a quoted text

![image](https://user-images.githubusercontent.com/5592397/87425415-4476ae80-c5e6-11ea-8c0b-ab2e57d0cdd5.png)

![image](https://user-images.githubusercontent.com/5592397/87425547-7e47b500-c5e6-11ea-8c3c-01d1942692e7.png)

**Comment by IvanMenshov** [comment]
Hello @IlyaMokin ,
I added changes to the UI.
https://ivanmenshov.github.io/whatsapp-ui/

**Comment by ilya4321** [comment]
Looks good, the task is ready. Please check your js tasks if you didn't check.  A task3 should be ready tomorrow.
